### ISSUE TITLE
No release for 0.4.3 to support :managed-dependencies

### ISSUE THREAD

**Issue by MatthewDarling** [sattvik/leinjacker#14]
I'd like to take the results of [my previous PR](https://github.com/sattvik/leinjacker/pull/13) and get them integrated into the plugins that use `leinjacker`. In order to do that, there needs to be a Clojars release of 0.4.3.

If there's anything I can do to help make that happen, I'm happy to do so!

**Comment by 0xbase12** [comment]
Could you release 0.4.3 to fix issue with managed-dependencies

**Comment by MatthewDarling** [comment]
If you're in a rush, we [set up a fork](https://github.com/kirasystems/leinjacker) so we could start using `:managed-dependencies` in our projects. Just use `[kirasystems/leinjacker "0.4.3"]`.

The trouble with plugins is I don't know of a way to control their dependencies from the outside. So we also [forked `codox`](https://github.com/kirasystems/codox) to use that version of `leinjacker`, available as: `[kirasystems/lein-codox "0.10.4"]`.

**Comment by 0xbase12** [comment]
Hi thanks for the workaround. Will use your fork. Thanks Matthew

**Comment by tobias** [comment]
I'll take a look at releasing 0.4.3 now. The build is broken with lein 2.8.1, so I'll see about fixing that first.

**Comment by jameslintaylor** [comment]
@tobias Any updates on a release cut?

**Comment by MatthewDarling** [comment]
Ah, looks like #15 has [a relevant comment](https://github.com/sattvik/leinjacker/pull/15#issuecomment-354933094):

> I tried to release 0.4.3 for #14, but lein release fails under lein 2.8.1 without this change to the midje versions.

So at a minimum that PR needs to go in before the release. May as well bring in #17 as well, for Clojure 1.10 support.

**Comment by tobias** [comment]
I finally got 0.4.3 out - sorry for the excessive delay:
https://clojars.org/leinjacker/versions/0.4.3
